version: "3.8"

services:
  app:
    image: mybyelias/test:latest
    container_name: app
    ports:
      - "8080:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all
    restart: always

volumes:
  mongo_data:

